### ISSUE TITLE
Script doesn't start.

### ISSUE THREAD

**Issue by nexitem** [Laberbear/pyload-clicknload#18]
A window pops up but just close.

Starting via powershell:

![image](https://user-images.githubusercontent.com/481247/191808182-88cf64f4-e244-4802-9e3d-c692ec1b1184.png)

**Comment by Laberbear** [comment]
You just exposed your pyload password and URL, I suggest you to read up on cyber security basics or remove yourself from electronic machinery!

Anyways your credentials are probably wrong and you need to update your pyloadConfig.json

**Comment by nexitem** [comment]
Bro, your password is inside that .exe you provided, I suggest you learn how to build your apps properly.

Start here:
https://blog.hubspot.com/website/how-to-start-coding

**Comment by Laberbear** [comment]
Fixed in https://github.com/Laberbear/pyload-clicknload/releases/tag/1.0.1
